apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
  namespace: ecommerce
  labels:
    app: cartservice
    component: backend
data:
  GRPC_PORT: "50057"
  APP_ENV: "production"

  # Redis
  REDIS_ENABLED: "true"
  REDIS_HOST: "redis-cart"
  REDIS_PORT: "6379"

  USER_SERVICE_GRPC_ADDR: "userservice.ecommerce.svc.cluster.local:50051"
  PRODUCT_SERVICE_GRPC_ADDR: "productservice.ecommerce.svc.cluster.local:50053"  

  # Tracing

