apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  JWT_SECRET: change-me-in-prod
  INTERNAL_AUTH_TOKEN: change-me-in-prod
  POSTGRES_PASSWORD: change-me-in-prod
  REDIS_PASSWORD: ""
  USER_DB_DSN: "host=user-db user=postgres password=change-me-in-prod dbname=userservice port=5432 sslmode=disable TimeZone=UTC"
  PRODUCT_DB_DSN: "host=product-db user=postgres password=change-me-in-prod dbname=products port=5432 sslmode=disable TimeZone=UTC"
  ORDER_DB_DSN: "host=order-db user=postgres password=change-me-in-prod dbname=orders port=5432 sslmode=disable TimeZone=UTC"
