apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-postgres
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-postgres
  template:
    metadata:
      labels:
        app: products-postgres
    spec:
      containers:
        - name: products-postgres
          image: postgres:15-alpine

          envFrom:
            - secretRef:
                name: products-postgres-secret

          ports:
            - containerPort: 5432

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-product-pvc

