apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-product-pv
  namespace: ecommerce
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-sc
  hostPath:
    path: /mnt/data/productspostgres
