apiVersion: v1
kind: Service
metadata:
  name: products-postgres
  namespace: ecommerce
spec:
  type: ClusterIP
  selector:
    app: products-postgres
  ports:
    - port: 5432
      targetPort: 5432

