apiVersion: v1
kind: ConfigMap
metadata:
  name: orderservice-config
  namespace: ecommerce
  labels:
    app: orderservice
data:
  # Application
  GRPC_PORT: "50055"
  APP_ENV: "production"

  # Database
  DB_DRIVER: "postgres"
  DB_MIGRATION_AUTO_RUN: "true"

  # Downstream gRPC services
  USER_SERVICE_GRPC_ADDR: "userservice.ecommerce.svc.cluster.local:50051"
  PRODUCT_SERVICE_GRPC_ADDR: "productservice.ecommerce.svc.cluster.local:50053"

  # Tracing
